export declare const makeEventChecker: (value: string, split?: string) => string;
export declare const CHECK_DOM_EVENT_PATTERN: RegExp;
export declare const CHECK_LOAD_PATTERN: RegExp;
export declare const CHECK_BIND_PATTERN: RegExp;
export declare const NAME_SAPARATOR = ":";
export declare const CHECK_SAPARATOR = "|";
export declare const DOM_EVENT_SAPARATOR = "dom ";
export declare const LOAD_SAPARATOR = "load ";
export declare const BIND_SAPARATOR = "bind ";
export declare const SAPARATOR = " ";
export declare const DOM_EVENT_MAKE: (...keys: any[]) => (...args: any[]) => string;
export declare const CUSTOM: (...keys: any[]) => (...args: any[]) => string;
export declare const CLICK: (...args: any[]) => string;
export declare const DOUBLECLICK: (...args: any[]) => string;
export declare const MOUSEDOWN: (...args: any[]) => string;
export declare const MOUSEUP: (...args: any[]) => string;
export declare const MOUSEMOVE: (...args: any[]) => string;
export declare const MOUSEOVER: (...args: any[]) => string;
export declare const MOUSEOUT: (...args: any[]) => string;
export declare const MOUSEENTER: (...args: any[]) => string;
export declare const MOUSELEAVE: (...args: any[]) => string;
export declare const TOUCHSTART: (...args: any[]) => string;
export declare const TOUCHMOVE: (...args: any[]) => string;
export declare const TOUCHEND: (...args: any[]) => string;
export declare const KEYDOWN: (...args: any[]) => string;
export declare const KEYUP: (...args: any[]) => string;
export declare const KEYPRESS: (...args: any[]) => string;
export declare const DRAG: (...args: any[]) => string;
export declare const DRAGSTART: (...args: any[]) => string;
export declare const DROP: (...args: any[]) => string;
export declare const DRAGOVER: (...args: any[]) => string;
export declare const DRAGENTER: (...args: any[]) => string;
export declare const DRAGLEAVE: (...args: any[]) => string;
export declare const DRAGEXIT: (...args: any[]) => string;
export declare const DRAGOUT: (...args: any[]) => string;
export declare const DRAGEND: (...args: any[]) => string;
export declare const CONTEXTMENU: (...args: any[]) => string;
export declare const CHANGE: (...args: any[]) => string;
export declare const INPUT: (...args: any[]) => string;
export declare const FOCUS: (...args: any[]) => string;
export declare const FOCUSIN: (...args: any[]) => string;
export declare const FOCUSOUT: (...args: any[]) => string;
export declare const BLUR: (...args: any[]) => string;
export declare const PASTE: (...args: any[]) => string;
export declare const RESIZE: (...args: any[]) => string;
export declare const SCROLL: (...args: any[]) => string;
export declare const SUBMIT: (...args: any[]) => string;
export declare const POINTERSTART: (...args: any[]) => string;
export declare const POINTERMOVE: (...args: any[]) => string;
export declare const POINTEREND: (...args: any[]) => string;
export declare const CHANGEINPUT: (...args: any[]) => string;
export declare const WHEEL: (...args: any[]) => string;
export declare const ANIMATIONSTART: (...args: any[]) => string;
export declare const ANIMATIONEND: (...args: any[]) => string;
export declare const ANIMATIONITERATION: (...args: any[]) => string;
export declare const TRANSITIONSTART: (...args: any[]) => string;
export declare const TRANSITIONEND: (...args: any[]) => string;
export declare const TRANSITIONRUN: (...args: any[]) => string;
export declare const TRANSITIONCANCEL: (...args: any[]) => string;
export declare const CHECKER: (value: string, split?: string) => string;
export declare const AFTER: (value: string, split?: string) => string;
export declare const BEFORE: (value: string, split?: string) => string;
export declare const IF: (value: string, split?: string) => string;
export declare const KEY: (value: string, split?: string) => string;
export declare const ARROW_UP: string;
export declare const ARROW_DOWN: string;
export declare const ARROW_LEFT: string;
export declare const ARROW_RIGHT: string;
export declare const ENTER: string;
export declare const SPACE: string;
export declare const ESCAPE: string;
export declare const ALT: string;
export declare const SHIFT: string;
export declare const META: string;
export declare const CONTROL: string;
export declare const SELF: string;
export declare const FIT: string;
export declare const PASSIVE: string;
export declare const VDOM: string;
export declare const DEBOUNCE: (t?: number) => string;
export declare const D1000: string;
export declare const THROTTLE: (t?: number) => string;
export declare const CAPTURE: string;
export declare const MOVE: (method?: string) => string;
export declare const END: (method?: string) => string;
export declare const PREVENT: string;
export declare const STOP: string;
export declare const LOAD: (value?: string) => string;
export declare const createRef: (value: any) => string;
export declare const getRef: (id: string) => any;
export declare const BIND_CHECK_DEFAULT_FUNCTION: () => boolean;
export declare const BIND: (value?: string, checkFieldOrCallback?: string) => string;
export interface CaptureOption {
    passive: boolean;
    capture: boolean;
}
export declare function addEvent(dom: HTMLElement | undefined, eventName: string, callback: () => void, useCapture?: boolean | CaptureOption): void;
export declare function removeEvent(dom: HTMLElement | undefined, eventName: string, callback: (() => void) | undefined): void;
interface PageXY {
    pageX: number;
    pageY: number;
}
export declare function pos(e: TouchEvent | MouseEvent): PageXY;
export interface Point {
    x: number;
    y: number;
}
export declare function posXY(e: TouchEvent | MouseEvent): Point;
export {};
